import type { Project, Milestone, EscrowTransaction, Bid, Product, Order, OrderItem, SupplierStore } from '@emaar/types';

// ═══════════════════════════════════════════════════════════════
// MOCK DATA — Used until backend integration is complete
// All mock data is well-typed against the shared types
// ═══════════════════════════════════════════════════════════════

const mockClientId = 'mock-client-id';
const mockContractorId = 'mock-contractor-id';
const mockRegionId = 'mock-region-riyadh';
const mockCategoryId = 'mock-category-finishing';

// ─── Currently signed-in contractor (for contractor views) ────
// Bids/projects belonging to "mock-contractor-A" represent the
// logged-in contractor's own data.
export const CURRENT_CONTRACTOR_ID = 'mock-contractor-A';

// ─── Currently signed-in supplier ─────────────────────────────
// The supplier views use mock-store-A as the logged-in store.
export const CURRENT_SUPPLIER_STORE_ID = 'mock-store-A';
export const CURRENT_SUPPLIER_USER_ID = 'mock-supplier-A';

export const mockRegions = [
  { id: 'mock-region-riyadh', nameAr: 'الرياض', nameEn: 'Riyadh' },
  { id: 'mock-region-jeddah', nameAr: 'جدة', nameEn: 'Jeddah' },
  { id: 'mock-region-dammam', nameAr: 'الدمام', nameEn: 'Dammam' },
  { id: 'mock-region-mecca', nameAr: 'مكة المكرمة', nameEn: 'Mecca' },
  { id: 'mock-region-medina', nameAr: 'المدينة المنورة', nameEn: 'Medina' },
];

export const mockCategories = [
  { id: 'mock-category-finishing', nameAr: 'تشطيب داخلي', nameEn: 'Interior Finishing', icon: '🎨' },
  { id: 'mock-category-construction', nameAr: 'بناء وإنشاء', nameEn: 'Construction', icon: '🏗️' },
  { id: 'mock-category-electrical', nameAr: 'كهرباء وإضاءة', nameEn: 'Electrical', icon: '💡' },
  { id: 'mock-category-plumbing', nameAr: 'سباكة', nameEn: 'Plumbing', icon: '🚰' },
  { id: 'mock-category-painting', nameAr: 'دهانات', nameEn: 'Painting', icon: '🖌️' },
  { id: 'mock-category-flooring', nameAr: 'أرضيات وسيراميك', nameEn: 'Flooring', icon: '◼️' },
  { id: 'mock-category-kitchens', nameAr: 'مطابخ ودواليب', nameEn: 'Kitchens', icon: '🍳' },
  { id: 'mock-category-hvac', nameAr: 'تكييف وتبريد', nameEn: 'HVAC', icon: '❄️' },
];

export const mockProjects: Project[] = [
  {
    id: 'mock-project-1',
    clientId: mockClientId,
    contractorId: 'mock-contractor-A',
    regionId: mockRegionId,
    titleAr: 'تشطيب فيلا حي الياسمين',
    titleEn: 'Yasmin District Villa Finishing',
    description: 'تشطيب كامل لفيلا سكنية مساحتها 450 متر مربع بمواصفات فاخرة تشمل الرخام الطبيعي والدهانات الإيطالية',
    categoryId: mockCategoryId,
    totalBudget: 480000,
    currency: 'SAR',
    status: 'IN_PROGRESS',
    address: { lat: 24.7136, lng: 46.6753, formattedAddress: 'حي الياسمين، الرياض' },
    startDate: '2026-03-15',
    expectedEnd: '2026-08-30',
    createdAt: '2026-03-10T10:00:00Z',
  },
  {
    id: 'mock-project-2',
    clientId: mockClientId,
    regionId: mockRegionId,
    titleAr: 'بناء مكتب تجاري - طريق الملك فهد',
    titleEn: 'Commercial Office Construction',
    description: 'بناء مبنى مكاتب تجارية من 4 طوابق على طريق الملك فهد',
    categoryId: 'mock-category-construction',
    totalBudget: 1850000,
    currency: 'SAR',
    status: 'BIDDING',
    address: { lat: 24.7136, lng: 46.6753, formattedAddress: 'طريق الملك فهد، الرياض' },
    createdAt: '2026-05-01T08:30:00Z',
  },
  {
    id: 'mock-project-3',
    clientId: mockClientId,
    regionId: mockRegionId,
    titleAr: 'تركيب نظام إضاءة ذكي - مجمع سكني',
    titleEn: 'Smart Lighting Installation',
    description: 'تركيب نظام إضاءة ذكي مع التحكم الكامل عبر تطبيق الجوال لمجمع سكني من 12 وحدة',
    categoryId: 'mock-category-electrical',
    totalBudget: 145000,
    currency: 'SAR',
    status: 'PUBLISHED',
    address: { lat: 24.7136, lng: 46.6753, formattedAddress: 'حي العليا، الرياض' },
    createdAt: '2026-05-10T14:20:00Z',
  },
  {
    id: 'mock-project-4',
    clientId: mockClientId,
    contractorId: 'mock-contractor-A',
    regionId: mockRegionId,
    titleAr: 'تجديد مطبخ شقة سكنية',
    titleEn: 'Kitchen Renovation',
    description: 'تجديد كامل لمطبخ شقة سكنية بمساحة 28 متر مربع',
    categoryId: 'mock-category-kitchens',
    totalBudget: 75000,
    currency: 'SAR',
    status: 'COMPLETED',
    address: { lat: 24.7136, lng: 46.6753, formattedAddress: 'حي الملقا، الرياض' },
    startDate: '2026-01-15',
    expectedEnd: '2026-02-28',
    actualEnd: '2026-02-25',
    createdAt: '2026-01-10T11:00:00Z',
  },
  {
    id: 'mock-project-5',
    clientId: 'mock-client-2',
    regionId: 'mock-region-jeddah',
    titleAr: 'تشطيب فلل سكنية - مشروع الواجهة البحرية',
    titleEn: 'Seafront Villas Finishing',
    description: 'تشطيب 3 فلل سكنية بمواصفات فاخرة على الواجهة البحرية، تشمل الرخام الإيطالي والإضاءة الذكية',
    categoryId: mockCategoryId,
    totalBudget: 1250000,
    currency: 'SAR',
    status: 'BIDDING',
    address: { lat: 21.4858, lng: 39.1925, formattedAddress: 'حي الشاطئ، جدة' },
    startDate: '2026-07-01',
    expectedEnd: '2027-01-30',
    createdAt: '2026-05-14T09:30:00Z',
  },
  {
    id: 'mock-project-6',
    clientId: 'mock-client-3',
    regionId: 'mock-region-riyadh',
    titleAr: 'إنشاء مستودع تجاري - حي الصناعية',
    titleEn: 'Commercial Warehouse Construction',
    description: 'بناء مستودع تجاري بمساحة 1200 متر مربع مع مكاتب إدارية ومنطقة تحميل',
    categoryId: 'mock-category-construction',
    totalBudget: 950000,
    currency: 'SAR',
    status: 'BIDDING',
    address: { lat: 24.7136, lng: 46.6753, formattedAddress: 'الحي الصناعي، الرياض' },
    startDate: '2026-06-15',
    expectedEnd: '2027-02-28',
    createdAt: '2026-05-15T11:00:00Z',
  },
  {
    id: 'mock-project-7',
    clientId: 'mock-client-4',
    regionId: 'mock-region-dammam',
    titleAr: 'تركيب نظام تكييف مركزي - مبنى مكاتب',
    titleEn: 'Central HVAC Installation',
    description: 'توريد وتركيب نظام تكييف مركزي حديث لمبنى مكاتب من 6 طوابق',
    categoryId: 'mock-category-hvac',
    totalBudget: 380000,
    currency: 'SAR',
    status: 'PUBLISHED',
    address: { lat: 26.4207, lng: 50.0888, formattedAddress: 'حي الراكة، الدمام' },
    createdAt: '2026-05-16T08:15:00Z',
  },
];

export const mockMilestones: Milestone[] = [
  {
    id: 'mock-milestone-1',
    projectId: 'mock-project-1',
    titleAr: 'الأعمال التحضيرية والكسر والإزالة',
    titleEn: 'Preparation & Demolition',
    description: 'إزالة التشطيبات السابقة وتجهيز الموقع',
    sequenceOrder: 1,
    amount: 60000,
    status: 'PAID',
    dueDate: '2026-04-01',
    submittedAt: '2026-03-28T16:00:00Z',
    approvedAt: '2026-03-29T10:30:00Z',
    proofMedia: [],
    checklist: [],
    createdAt: '2026-03-15T10:00:00Z',
  },
  {
    id: 'mock-milestone-2',
    projectId: 'mock-project-1',
    titleAr: 'أعمال السباكة والكهرباء',
    titleEn: 'Plumbing & Electrical',
    description: 'تنفيذ شبكة السباكة والتمديدات الكهربائية',
    sequenceOrder: 2,
    amount: 120000,
    status: 'APPROVED',
    dueDate: '2026-05-15',
    submittedAt: '2026-05-12T14:00:00Z',
    approvedAt: '2026-05-14T09:15:00Z',
    proofMedia: [],
    checklist: [],
    createdAt: '2026-03-15T10:00:00Z',
  },
  {
    id: 'mock-milestone-3',
    projectId: 'mock-project-1',
    titleAr: 'أعمال الجبس والدهانات',
    titleEn: 'Plaster & Paint',
    description: 'تنفيذ تصميمات الجبس بورد وأعمال الدهانات الفاخرة',
    sequenceOrder: 3,
    amount: 140000,
    status: 'IN_PROGRESS',
    dueDate: '2026-06-30',
    proofMedia: [],
    checklist: [],
    createdAt: '2026-03-15T10:00:00Z',
  },
  {
    id: 'mock-milestone-4',
    projectId: 'mock-project-1',
    titleAr: 'الأرضيات والرخام',
    titleEn: 'Flooring & Marble',
    description: 'توريد وتركيب الرخام الطبيعي والأرضيات',
    sequenceOrder: 4,
    amount: 100000,
    status: 'PENDING',
    dueDate: '2026-07-30',
    proofMedia: [],
    checklist: [],
    createdAt: '2026-03-15T10:00:00Z',
  },
  {
    id: 'mock-milestone-5',
    projectId: 'mock-project-1',
    titleAr: 'التشطيبات النهائية والتسليم',
    titleEn: 'Final Touches & Handover',
    description: 'التشطيبات النهائية والتنظيف والتسليم النهائي',
    sequenceOrder: 5,
    amount: 60000,
    status: 'PENDING',
    dueDate: '2026-08-30',
    proofMedia: [],
    checklist: [],
    createdAt: '2026-03-15T10:00:00Z',
  },
];

export const mockEscrowTransactions: EscrowTransaction[] = [
  {
    id: 'mock-escrow-1',
    milestoneId: 'mock-milestone-1',
    projectId: 'mock-project-1',
    payerId: mockClientId,
    payeeId: mockContractorId,
    totalAmount: 60000,
    heldAmount: 0,
    releasedAmount: 60000,
    platformFee: 3000,
    status: 'RELEASED',
    fundedAt: '2026-03-20T10:00:00Z',
    releasedAt: '2026-03-29T10:30:00Z',
    createdAt: '2026-03-15T10:00:00Z',
  },
  {
    id: 'mock-escrow-2',
    milestoneId: 'mock-milestone-2',
    projectId: 'mock-project-1',
    payerId: mockClientId,
    payeeId: mockContractorId,
    totalAmount: 120000,
    heldAmount: 0,
    releasedAmount: 120000,
    platformFee: 6000,
    status: 'RELEASED',
    fundedAt: '2026-05-01T11:00:00Z',
    releasedAt: '2026-05-14T09:15:00Z',
    createdAt: '2026-04-30T10:00:00Z',
  },
  {
    id: 'mock-escrow-3',
    milestoneId: 'mock-milestone-3',
    projectId: 'mock-project-1',
    payerId: mockClientId,
    payeeId: mockContractorId,
    totalAmount: 140000,
    heldAmount: 140000,
    releasedAmount: 0,
    platformFee: 7000,
    status: 'HELD',
    fundedAt: '2026-05-20T13:00:00Z',
    createdAt: '2026-05-19T10:00:00Z',
  },
];

export const mockBids: Bid[] = [
  {
    id: 'mock-bid-1',
    projectId: 'mock-project-2',
    contractorId: 'mock-contractor-A',
    amount: 1750000,
    duration: 240,
    proposal: 'خبرة 15 عاماً في تنفيذ المباني التجارية. سنستخدم أعلى المعايير الهندسية مع ضمان شامل لمدة سنتين.',
    status: 'PENDING',
    createdAt: '2026-05-12T10:00:00Z',
  },
  {
    id: 'mock-bid-2',
    projectId: 'mock-project-2',
    contractorId: 'mock-contractor-B',
    amount: 1820000,
    duration: 210,
    proposal: 'لدينا فريق هندسي معتمد وآلات حديثة. نعد بتسليم أسرع مع نفس مستوى الجودة.',
    status: 'PENDING',
    createdAt: '2026-05-13T14:30:00Z',
  },
  {
    id: 'mock-bid-3',
    projectId: 'mock-project-2',
    contractorId: 'mock-contractor-C',
    amount: 1690000,
    duration: 270,
    proposal: 'أفضل سعر مع التزام بالجودة. مشاريع سابقة مماثلة تشمل برج الراجحي وفلل المرسى.',
    status: 'PENDING',
    createdAt: '2026-05-14T09:15:00Z',
  },
  // Bid by current contractor (mock-contractor-A) on project-5
  {
    id: 'mock-bid-4',
    projectId: 'mock-project-5',
    contractorId: 'mock-contractor-A',
    amount: 1180000,
    duration: 195,
    proposal: 'خبرة طويلة في تشطيب الفلل الفاخرة على الواجهة البحرية. سنستخدم رخاماً إيطالياً معتمداً وفريقاً متخصصاً في الإضاءة الذكية.',
    status: 'PENDING',
    createdAt: '2026-05-15T11:30:00Z',
  },
  // Accepted bid (won — became contractor of project-1)
  {
    id: 'mock-bid-5',
    projectId: 'mock-project-1',
    contractorId: 'mock-contractor-A',
    amount: 480000,
    duration: 165,
    proposal: 'تنفيذ احترافي بأعلى معايير الجودة والشفافية.',
    status: 'ACCEPTED',
    createdAt: '2026-03-08T10:00:00Z',
  },
  // Rejected bid (didn't win)
  {
    id: 'mock-bid-6',
    projectId: 'mock-project-6',
    contractorId: 'mock-contractor-A',
    amount: 920000,
    duration: 240,
    proposal: 'فريقنا متخصص في إنشاء المستودعات التجارية مع مراعاة تامة للمعايير الإنشائية والسلامة.',
    status: 'PENDING',
    createdAt: '2026-05-16T14:00:00Z',
  },
];

export const mockContractors = [
  {
    id: 'mock-contractor-A',
    fullNameAr: 'شركة البناء الذهبي',
    qualityRating: 4.8,
    totalProjects: 47,
    specializations: ['بناء', 'مباني تجارية', 'تشطيب فاخر'],
  },
  {
    id: 'mock-contractor-B',
    fullNameAr: 'مؤسسة العمران الحديثة',
    qualityRating: 4.6,
    totalProjects: 32,
    specializations: ['بناء', 'تشطيب', 'كهرباء'],
  },
  {
    id: 'mock-contractor-C',
    fullNameAr: 'شركة المعمار الأنيق',
    qualityRating: 4.9,
    totalProjects: 89,
    specializations: ['بناء', 'تشطيب فاخر', 'استشارات هندسية'],
  },
];

// ═══════════════════════════════════════════════════════════════
// SUPPLIER STORES & PRODUCTS
// ═══════════════════════════════════════════════════════════════

export const mockSupplierStore: SupplierStore = {
  id: 'mock-store-A',
  userId: 'mock-supplier-A',
  storeNameAr: 'إعمار للإضاءات والمواد الفاخرة',
  storeNameEn: 'Emaar Premium Lighting & Materials',
  categoryId: 'mock-category-electrical',
  licenseNumber: 'CR-1010234567',
  rating: 4.7,
  deliveryZones: [],
  commissionRate: 3.5,
  isVerified: true,
};

// All stores in marketplace (public listing)
export const mockAllStores: SupplierStore[] = [
  mockSupplierStore,
  {
    id: 'mock-store-B',
    userId: 'mock-supplier-B',
    storeNameAr: 'الرخام الملكي للأرضيات',
    storeNameEn: 'Royal Marble Flooring',
    categoryId: 'mock-category-flooring',
    licenseNumber: 'CR-1010987654',
    rating: 4.9,
    deliveryZones: [],
    commissionRate: 3.0,
    isVerified: true,
  },
  {
    id: 'mock-store-C',
    userId: 'mock-supplier-C',
    storeNameAr: 'بيت الدهانات الإيطالية',
    storeNameEn: 'Italian Paint House',
    categoryId: 'mock-category-painting',
    licenseNumber: 'CR-1010445566',
    rating: 4.6,
    deliveryZones: [],
    commissionRate: 4.0,
    isVerified: true,
  },
  {
    id: 'mock-store-D',
    userId: 'mock-supplier-D',
    storeNameAr: 'مطابخ المهندس',
    storeNameEn: 'Engineer Kitchens',
    categoryId: 'mock-category-kitchens',
    licenseNumber: 'CR-1010778899',
    rating: 4.5,
    deliveryZones: [],
    commissionRate: 3.5,
    isVerified: false,
  },
];

export const mockProducts: Product[] = [
  {
    id: 'mock-product-1',
    storeId: 'mock-store-A',
    nameAr: 'ثريا كريستالية فاخرة - 24 ضوءاً',
    nameEn: 'Luxury Crystal Chandelier - 24 Lights',
    descriptionAr: 'ثريا كريستالية إيطالية الصنع بـ 24 ضوءاً LED، مناسبة للصالات الفاخرة',
    descriptionEn: 'Italian-made crystal chandelier with 24 LED lights',
    categoryId: 'mock-category-electrical',
    price: 12500,
    currency: 'SAR',
    stockQuantity: 8,
    unit: 'قطعة',
    images: [],
    isActive: true,
    createdAt: '2026-04-15T10:00:00Z',
  },
  {
    id: 'mock-product-2',
    storeId: 'mock-store-A',
    nameAr: 'سبوت LED مدمج - 9 وات',
    nameEn: 'Recessed LED Spotlight - 9W',
    descriptionAr: 'إضاءة سبوت LED 9 وات بدرجة إضاءة 4000K، مع ضمان 5 سنوات',
    descriptionEn: 'Recessed LED spotlight 9W, 4000K, 5-year warranty',
    categoryId: 'mock-category-electrical',
    price: 85,
    currency: 'SAR',
    stockQuantity: 450,
    unit: 'قطعة',
    images: [],
    isActive: true,
    createdAt: '2026-04-10T08:30:00Z',
  },
  {
    id: 'mock-product-3',
    storeId: 'mock-store-A',
    nameAr: 'رخام كرارا إيطالي - متر مربع',
    nameEn: 'Italian Carrara Marble',
    descriptionAr: 'رخام كرارا إيطالي طبيعي مصقول، مقاس 60×120 سم، سماكة 2 سم',
    descriptionEn: 'Natural polished Italian Carrara marble, 60×120cm, 2cm thickness',
    categoryId: 'mock-category-flooring',
    price: 480,
    currency: 'SAR',
    stockQuantity: 2400,
    unit: 'متر مربع',
    images: [],
    isActive: true,
    createdAt: '2026-03-20T14:00:00Z',
  },
  {
    id: 'mock-product-4',
    storeId: 'mock-store-A',
    nameAr: 'دهان جوتن أبيض ثلج - 18 لتر',
    nameEn: 'Jotun Snow White Paint - 18L',
    descriptionAr: 'دهان داخلي مات أبيض ثلج، تغطية ممتازة وسهل التنظيف',
    descriptionEn: 'Premium matte white interior paint with excellent coverage',
    categoryId: 'mock-category-painting',
    price: 425,
    currency: 'SAR',
    stockQuantity: 120,
    unit: 'علبة 18 لتر',
    images: [],
    isActive: true,
    createdAt: '2026-04-01T09:00:00Z',
  },
  {
    id: 'mock-product-5',
    storeId: 'mock-store-A',
    nameAr: 'خلاط مطبخ ستانلس مع رشاش',
    nameEn: 'Stainless Steel Kitchen Mixer with Sprayer',
    descriptionAr: 'خلاط مطبخ ألماني ستانلس ستيل مع رشاش قابل للسحب وضمان 10 سنوات',
    descriptionEn: 'German stainless steel kitchen mixer with pull-out sprayer, 10-year warranty',
    categoryId: 'mock-category-kitchens',
    price: 1850,
    currency: 'SAR',
    stockQuantity: 35,
    unit: 'قطعة',
    images: [],
    isActive: true,
    createdAt: '2026-04-12T11:30:00Z',
  },
  {
    id: 'mock-product-6',
    storeId: 'mock-store-A',
    nameAr: 'سخان مياه كهربائي - 80 لتر',
    nameEn: 'Electric Water Heater - 80L',
    descriptionAr: 'سخان مياه كهربائي تركي الصنع بسعة 80 لتر مع ترموستات رقمي',
    descriptionEn: 'Turkish electric water heater 80L with digital thermostat',
    categoryId: 'mock-category-plumbing',
    price: 1245,
    currency: 'SAR',
    stockQuantity: 0,
    unit: 'قطعة',
    images: [],
    isActive: true,
    createdAt: '2026-03-25T13:15:00Z',
  },
  {
    id: 'mock-product-7',
    storeId: 'mock-store-A',
    nameAr: 'سيراميك بورسلين فاخر - 80×80',
    nameEn: 'Premium Porcelain Tiles - 80×80',
    descriptionAr: 'بلاط بورسلين إسباني فاخر، مقاوم للخدش والبهتان، مقاس 80×80 سم',
    descriptionEn: 'Premium Spanish porcelain tiles, scratch and fade resistant',
    categoryId: 'mock-category-flooring',
    price: 145,
    currency: 'SAR',
    stockQuantity: 850,
    unit: 'متر مربع',
    images: [],
    isActive: true,
    createdAt: '2026-04-05T10:45:00Z',
  },
  {
    id: 'mock-product-8',
    storeId: 'mock-store-A',
    nameAr: 'مكيف سبليت إنفرتر - 24,000 وحدة',
    nameEn: 'Inverter Split AC - 24,000 BTU',
    descriptionAr: 'مكيف سبليت إنفرتر موفر للطاقة بقدرة 24,000 وحدة، تصنيف A++',
    descriptionEn: 'Energy-saving inverter split AC, 24,000 BTU, A++ rating',
    categoryId: 'mock-category-hvac',
    price: 3850,
    currency: 'SAR',
    stockQuantity: 18,
    unit: 'قطعة',
    images: [],
    isActive: true,
    createdAt: '2026-04-20T15:20:00Z',
  },
  {
    id: 'mock-product-9',
    storeId: 'mock-store-A',
    nameAr: 'إضاءة LED شريطية مرنة - 5 متر',
    nameEn: 'Flexible LED Strip - 5m',
    descriptionAr: 'شريط إضاءة LED مرن RGB قابل للتحكم بتطبيق الجوال',
    descriptionEn: 'Flexible RGB LED strip with mobile app control',
    categoryId: 'mock-category-electrical',
    price: 220,
    currency: 'SAR',
    stockQuantity: 95,
    unit: 'لفة 5 متر',
    images: [],
    isActive: false,
    createdAt: '2026-02-28T08:00:00Z',
  },
  {
    id: 'mock-product-10',
    storeId: 'mock-store-A',
    nameAr: 'مغسلة رخامية فاخرة',
    nameEn: 'Premium Marble Sink',
    descriptionAr: 'مغسلة رخامية طبيعية فاخرة مع مرآة LED مدمجة',
    descriptionEn: 'Premium natural marble sink with built-in LED mirror',
    categoryId: 'mock-category-plumbing',
    price: 2950,
    currency: 'SAR',
    stockQuantity: 12,
    unit: 'قطعة',
    images: [],
    isActive: true,
    createdAt: '2026-04-08T12:00:00Z',
  },
];

// ═══════════════════════════════════════════════════════════════
// ORDERS & ORDER ITEMS
// ═══════════════════════════════════════════════════════════════

export const mockOrders: Order[] = [
  {
    id: 'mock-order-1',
    projectId: 'mock-project-1',
    buyerId: 'mock-contractor-A',
    storeId: 'mock-store-A',
    totalAmount: 14625,
    status: 'PENDING',
    deliveryAddress: { lat: 24.7136, lng: 46.6753, formattedAddress: 'حي الياسمين، الرياض' },
    createdAt: '2026-05-16T14:30:00Z',
  },
  {
    id: 'mock-order-2',
    buyerId: mockClientId,
    storeId: 'mock-store-A',
    totalAmount: 38500,
    status: 'CONFIRMED',
    deliveryAddress: { lat: 24.7136, lng: 46.6753, formattedAddress: 'حي العليا، الرياض' },
    createdAt: '2026-05-15T10:15:00Z',
  },
  {
    id: 'mock-order-3',
    projectId: 'mock-project-1',
    buyerId: 'mock-contractor-A',
    storeId: 'mock-store-A',
    totalAmount: 8500,
    status: 'PREPARING',
    deliveryAddress: { lat: 24.7136, lng: 46.6753, formattedAddress: 'حي الياسمين، الرياض' },
    createdAt: '2026-05-13T09:00:00Z',
  },
  {
    id: 'mock-order-4',
    buyerId: 'mock-contractor-B',
    storeId: 'mock-store-A',
    totalAmount: 22300,
    status: 'SHIPPED',
    deliveryAddress: { lat: 24.7136, lng: 46.6753, formattedAddress: 'حي الملقا، الرياض' },
    trackingInfo: { carrier: 'شحن إعمار', trackingNumber: 'EMAR-2026-8842' },
    createdAt: '2026-05-10T13:45:00Z',
  },
  {
    id: 'mock-order-5',
    projectId: 'mock-project-4',
    buyerId: 'mock-contractor-A',
    storeId: 'mock-store-A',
    totalAmount: 5450,
    status: 'DELIVERED',
    deliveryAddress: { lat: 24.7136, lng: 46.6753, formattedAddress: 'حي الملقا، الرياض' },
    createdAt: '2026-04-20T11:00:00Z',
    deliveredAt: '2026-04-25T14:30:00Z',
  },
  {
    id: 'mock-order-6',
    buyerId: mockClientId,
    storeId: 'mock-store-A',
    totalAmount: 7720,
    status: 'DELIVERED',
    deliveryAddress: { lat: 24.7136, lng: 46.6753, formattedAddress: 'حي العليا، الرياض' },
    createdAt: '2026-04-12T08:30:00Z',
    deliveredAt: '2026-04-18T10:00:00Z',
  },
  {
    id: 'mock-order-7',
    buyerId: 'mock-contractor-C',
    storeId: 'mock-store-A',
    totalAmount: 3245,
    status: 'CANCELLED',
    deliveryAddress: { lat: 24.7136, lng: 46.6753, formattedAddress: 'حي السليمانية، الرياض' },
    createdAt: '2026-05-08T16:00:00Z',
  },
];

export const mockOrderItems: OrderItem[] = [
  // order-1: Crystal chandelier + 25 spotlights
  { id: 'mock-oi-1-1', orderId: 'mock-order-1', productId: 'mock-product-1', quantity: 1, unitPrice: 12500, totalPrice: 12500 },
  { id: 'mock-oi-1-2', orderId: 'mock-order-1', productId: 'mock-product-2', quantity: 25, unitPrice: 85, totalPrice: 2125 },

  // order-2: Marble + porcelain tiles
  { id: 'mock-oi-2-1', orderId: 'mock-order-2', productId: 'mock-product-3', quantity: 60, unitPrice: 480, totalPrice: 28800 },
  { id: 'mock-oi-2-2', orderId: 'mock-order-2', productId: 'mock-product-7', quantity: 67, unitPrice: 145, totalPrice: 9700 },

  // order-3: Paint + kitchen mixer
  { id: 'mock-oi-3-1', orderId: 'mock-order-3', productId: 'mock-product-4', quantity: 12, unitPrice: 425, totalPrice: 5100 },
  { id: 'mock-oi-3-2', orderId: 'mock-order-3', productId: 'mock-product-5', quantity: 1, unitPrice: 1850, totalPrice: 1850 },
  { id: 'mock-oi-3-3', orderId: 'mock-order-3', productId: 'mock-product-2', quantity: 18, unitPrice: 85, totalPrice: 1530 },

  // order-4: AC units + LED strips
  { id: 'mock-oi-4-1', orderId: 'mock-order-4', productId: 'mock-product-8', quantity: 5, unitPrice: 3850, totalPrice: 19250 },
  { id: 'mock-oi-4-2', orderId: 'mock-order-4', productId: 'mock-product-9', quantity: 14, unitPrice: 220, totalPrice: 3080 },

  // order-5: Marble sink
  { id: 'mock-oi-5-1', orderId: 'mock-order-5', productId: 'mock-product-10', quantity: 1, unitPrice: 2950, totalPrice: 2950 },
  { id: 'mock-oi-5-2', orderId: 'mock-order-5', productId: 'mock-product-5', quantity: 1, unitPrice: 1850, totalPrice: 1850 },
  { id: 'mock-oi-5-3', orderId: 'mock-order-5', productId: 'mock-product-2', quantity: 8, unitPrice: 85, totalPrice: 680 },

  // order-6: Mixed
  { id: 'mock-oi-6-1', orderId: 'mock-order-6', productId: 'mock-product-7', quantity: 35, unitPrice: 145, totalPrice: 5075 },
  { id: 'mock-oi-6-2', orderId: 'mock-order-6', productId: 'mock-product-4', quantity: 6, unitPrice: 425, totalPrice: 2550 },

  // order-7: Cancelled
  { id: 'mock-oi-7-1', orderId: 'mock-order-7', productId: 'mock-product-2', quantity: 38, unitPrice: 85, totalPrice: 3230 },
];

// Mock buyers (for displaying buyer names in orders)
export const mockBuyers: Record<string, { fullNameAr: string; phone: string; type: string }> = {
  'mock-contractor-A': { fullNameAr: 'شركة البناء الذهبي', phone: '+966501234567', type: 'مقاول' },
  'mock-contractor-B': { fullNameAr: 'مؤسسة العمران الحديثة', phone: '+966502345678', type: 'مقاول' },
  'mock-contractor-C': { fullNameAr: 'شركة المعمار الأنيق', phone: '+966503456789', type: 'مقاول' },
  'mock-client-id': { fullNameAr: 'أحمد عبدالله الشمري', phone: '+966504567890', type: 'عميل' },
};
